name: Build RustDesk

on:
  push:
    branches:
      - master  # Замените на вашу ветку
  pull_request:
    branches:
      - master  # Замените на вашу ветку

jobs:
  build:
    runs-on: ubuntu-22.04  # Используем конкретную версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Инициализируем подмодули

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-

      - name: Install system dependencies
        run: sudo apt-get install -y libssl-dev pkg-config

      - name: Build the project
        run: cargo build --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rustdesk-binaries
          path: target/release/
